name: Test Suite

on: [push, pull_request]

jobs:
  nui_preformatting_tests:
    name: Tests for NUI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/phone
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies NUI
        run: yarn --frozen-lockfile
      - name: Check build status
        run: yarn build
        env:
          CI: true

  game_scripts_test:
    name: Tests for Game Scripts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/game
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies NUI
        run: yarn --frozen-lockfile
      - name: Check build status
        run: yarn build
        env:
          CI: true


  lint:
    name: Lint Lua scripts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/game 
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: GoatG33k/fivem-lua-lint-action@v1
